Fix ReadOnly Error when Loading Climatology
Newer environments (e.g. python 3.12) would raise error about lon coordinate of climatology being read only when trying to roll across +-180 degrees, (i.e. lon.flags.writeable was False)
This is likely because of changes in dependencies and whether views or copies are returned.

Now always force copy.

Original Error Message:
```
ValueError                                Traceback (most recent call last)
Cell In[6], line 11
      7 if (vname in ['temp', 'sst', 'salt', 'sss', 'pdens'] or 'sigma' in vname) and (depth != 'bottom'):
      8     ts = clock.time()
      9     if   vname in ['temp', 'sst'] and  which_clim.lower()=='woa18': clim_vname = 't00an1'
     10     elif vname in ['salt', 'sss'] and  which_clim.lower()=='woa18': clim_vname = 's00an1'
---> 11     clim = tpv.load_climatology(mesh, clim_path, clim_vname, depth=depth)
     12     print(' --> elasped time to load clim: {:3.2f} min.'.format( (clock.time()-ts)/60  ))
     13     print(' --> clim uses {:3.2f} Gb:'.format(clim.nbytes/(1024**3)))
     14     print('')

File ~/tripyview/tripyview/sub_climatology.py:182, in load_climatology(mesh, datapath, vname, mon, depth, depidx, do_zarithm, do_hinterp, do_zinterp, descript, do_ptemp, pref, do_compute, do_load, do_persist, do_zweight, do_hweight, chunks, do_parallel, **kwargs)
    180     idx = np.where(lon>mesh.focus+180.0)[0]
    181     idx_roll = idx[0]
--> 182     lon[idx] = lon[idx]-360.0
    183 elif any(lon<mesh.focus-180.0):
    184     idx = np.where(lon<mesh.focus+180.0)[0]

ValueError: assignment destination is read-only
```